import fs from 'fs/promises';
import path from 'path';
import { spawn } from 'child_process';
import slugify from 'slugify';
import compressing from 'compressing';
import BuildJob from '../models/BuildJob.js';
import Project from '../models/Project.js';
import { env } from '../config/env.js';
import { ensureProjectDir } from './storage.service.js';

function appendLog(lines, line) {
  lines.push(`[${new Date().toISOString()}] ${line}`);
}

function runCommand(command, args, options = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      shell: process.platform === 'win32',
      ...options
    });

    let stdout = '';
    let stderr = '';

    child.stdout?.on('data', (chunk) => {
      stdout += chunk.toString();
    });
    child.stderr?.on('data', (chunk) => {
      stderr += chunk.toString();
    });

    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) resolve({ stdout, stderr });
      else reject(new Error(stderr || stdout || `Command failed with code ${code}`));
    });

    if (options.timeout) {
      setTimeout(() => {
        if (!child.killed) child.kill('SIGTERM');
      }, options.timeout);
    }
  });
}

async function zipDirectory(sourceDir, outPath) {
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await compressing.zip.compressDir(sourceDir, outPath);
}

async function locateFile(rootDir, filenames) {
  const stack = [rootDir];
  while (stack.length) {
    const current = stack.pop();
    const entries = await fs.readdir(current, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(current, entry.name);
      if (entry.isDirectory()) stack.push(fullPath);
      else if (filenames.includes(entry.name)) return fullPath;
    }
  }
  return '';
}

async function locateArtifacts(dir) {
  const apkPath = await locateFile(dir, ['app-release-signed.apk', 'app-release.apk', 'app-debug.apk']);
  const aabPath = await locateFile(dir, ['app-release-bundle.aab', 'app-release.aab']);
  return { apkPath, aabPath };
}

async function writeProjectReadme(project, dir) {
  const content = `# ${project.appName}

Generated by ${env.APP_NAME}.

- Site URL: ${project.siteUrl || 'n/a'}
- Source type: ${project.sourceType}
- Package ID: ${project.packageId}
- Launcher name: ${project.launcherName}
- Platforms: ${(project.requestedPlatforms || []).join(', ')}
- Generated: ${new Date().toISOString()}
`;
  await fs.writeFile(path.join(dir, 'PROJECT-README.md'), content, 'utf8');
}

async function writeStoreReviewPack(project, dir) {
  const reviewPack = {
    appName: project.appName,
    launcherName: project.launcherName,
    packageId: project.packageId,
    sourceType: project.sourceType,
    sourceUrl: project.siteUrl || '',
    requestedPlatforms: project.requestedPlatforms || [],
    validation: project.validation,
    notes: {
      android: 'Google Play acceptance depends on your app content, policy compliance, target SDK, privacy disclosures, icons, screenshots, and the final signed AAB uploaded to Play Console.',
      ios: 'Apple App Store acceptance depends on Apple review, account status, privacy disclosures, app quality, and a final build signed and submitted from Xcode on macOS.'
    },
    generatedAt: new Date().toISOString()
  };
  const reviewPath = path.join(dir, 'store-review-pack.json');
  await fs.writeFile(reviewPath, JSON.stringify(reviewPack, null, 2), 'utf8');
  return reviewPath;
}

async function writeIosHandoff(project, dir) {
  const iosDir = path.join(dir, 'ios-handoff');
  await fs.mkdir(iosDir, { recursive: true });
  const files = {
    'README-IOS.txt': `iOS submission handoff for ${project.appName}

This package is generated by Life Builder to prepare iOS delivery details.
Final IPA signing and App Store submission still require Xcode on macOS and an Apple Developer account.

Package ID: ${project.packageId}
Display Name: ${project.launcherName}
Hosted URL: ${project.siteUrl || 'Upload-based project'}
`,
    'app-config.json': JSON.stringify({
      appName: project.appName,
      launcherName: project.launcherName,
      bundleId: project.packageId,
      startUrl: project.siteUrl || '',
      validation: project.validation,
      requestedPlatforms: project.requestedPlatforms
    }, null, 2),
    'app-store-checklist.md': `# App Store checklist

- Confirm legal ownership of the site/app content.
- Prepare privacy policy URL.
- Prepare support URL.
- Prepare screenshots for iPhone and iPad if needed.
- Open the project in Xcode on macOS.
- Configure signing with your Apple Developer team.
- Archive and submit using App Store Connect.
`
  };

  for (const [name, content] of Object.entries(files)) {
    await fs.writeFile(path.join(iosDir, name), content, 'utf8');
  }

  const zipPath = path.join(env.STORAGE_DIR, 'exports', `${String(project._id)}-${project.packageId.replace(/[^a-zA-Z0-9._-]/g, '_')}-ios-handoff.zip`);
  await zipDirectory(iosDir, zipPath);
  return zipPath;
}

async function writeUploadedSourceCopy(project, dir) {
  const relative = project.artifacts?.uploadedZipRelativePath;
  if (!relative) return '';
  const src = path.join(env.STORAGE_DIR, relative);
  const dest = path.join(dir, path.basename(src));
  await fs.copyFile(src, dest);
  return dest;
}

async function buildWithBubblewrap(project, dir, logs) {
  const manifestUrl = project.validation.manifestUrl || `${project.normalizedSiteUrl}/manifest.webmanifest`;
  appendLog(logs, `Using manifest URL: ${manifestUrl}`);

  await runCommand('bubblewrap', ['init', '--manifest', manifestUrl, '--directory', dir], { cwd: dir, timeout: env.BUILD_TIMEOUT_MS });
  appendLog(logs, 'Bubblewrap init completed.');

  const twaManifestPath = path.join(dir, 'twa-manifest.json');
  const raw = await fs.readFile(twaManifestPath, 'utf8');
  const current = JSON.parse(raw);
  current.packageId = project.packageId;
  current.name = project.appName;
  current.launcherName = project.launcherName;
  current.startUrl = project.normalizedSiteUrl;
  current.host = new URL(project.normalizedSiteUrl).host;
  current.display = 'standalone';
  current.appVersionName = current.appVersionName || '1.0.0';
  current.appVersionCode = current.appVersionCode || 1;
  await fs.writeFile(twaManifestPath, JSON.stringify(current, null, 2), 'utf8');
  appendLog(logs, 'twa-manifest.json normalized for project values.');

  await runCommand('bubblewrap', ['build'], { cwd: dir, timeout: env.BUILD_TIMEOUT_MS });
  appendLog(logs, 'Bubblewrap build completed.');
}

export async function buildProjectArtifacts(projectId) {
  const project = await Project.findById(projectId);
  if (!project) throw new Error('Project not found.');

  project.status = 'building';
  project.lastBuildError = '';
  await project.save();

  const job = await BuildJob.create({
    projectId: project._id,
    status: 'running',
    strategy: 'hybrid',
    platforms: project.requestedPlatforms || ['android'],
    startedAt: new Date(),
    logs: []
  });

  const logs = [];
  const dir = await ensureProjectDir(project._id);

  try {
    appendLog(logs, `Preparing build directory: ${dir}`);
    await writeProjectReadme(project, dir);
    await writeUploadedSourceCopy(project, dir);
    const reviewPackPath = await writeStoreReviewPack(project, dir);
    const iosHandoffZip = project.requestedPlatforms?.includes('ios') ? await writeIosHandoff(project, dir) : '';

    if (project.requestedPlatforms?.includes('android')) {
      if (project.sourceType === 'url' && project.validation?.buildReady && env.ENABLE_ANDROID_BUILDS) {
        await buildWithBubblewrap(project, dir, logs);
        const { apkPath, aabPath } = await locateArtifacts(dir);
        if (!apkPath) throw new Error('Bubblewrap build finished without producing an APK artifact.');
        project.artifacts.apkRelativePath = path.relative(env.STORAGE_DIR, apkPath).replaceAll(path.sep, '/');
        if (aabPath) project.artifacts.aabRelativePath = path.relative(env.STORAGE_DIR, aabPath).replaceAll(path.sep, '/');
        appendLog(logs, 'Android Bubblewrap artifacts were generated successfully.');
      } else {
        appendLog(logs, 'Android Bubblewrap build was not run. Life Builder exported the source and review pack instead. Enable Android builds and use a hosted PWA URL to generate APK/AAB automatically.');
      }
    }

    const projectZipPath = path.join(env.STORAGE_DIR, 'builds', `${String(project._id)}-${project.packageId.replace(/[^a-zA-Z0-9._-]/g, '_')}-project-export.zip`);
    await zipDirectory(dir, projectZipPath);
    appendLog(logs, `Project export archive created: ${projectZipPath}`);

    const buildLogPath = path.join(dir, 'build.log');
    await fs.writeFile(buildLogPath, logs.join('\n'), 'utf8');

    project.artifacts.projectZipRelativePath = path.relative(env.STORAGE_DIR, projectZipPath).replaceAll(path.sep, '/');
    project.artifacts.androidProjectRelativePath = path.relative(env.STORAGE_DIR, dir).replaceAll(path.sep, '/');
    project.artifacts.reviewPackRelativePath = path.relative(env.STORAGE_DIR, reviewPackPath).replaceAll(path.sep, '/');
    project.artifacts.iosHandoffZipRelativePath = iosHandoffZip ? path.relative(env.STORAGE_DIR, iosHandoffZip).replaceAll(path.sep, '/') : '';
    project.artifacts.buildLogRelativePath = path.relative(env.STORAGE_DIR, buildLogPath).replaceAll(path.sep, '/');
    project.artifacts.builtAt = new Date();
    project.status = 'built';
    await project.save();

    job.status = 'completed';
    job.logs = logs;
    job.finishedAt = new Date();
    await job.save();

    return { project, job };
  } catch (error) {
    appendLog(logs, `Build failed: ${error.message}`);
    const buildLogPath = path.join(dir, 'build.log');
    await fs.writeFile(buildLogPath, logs.join('\n'), 'utf8');

    project.status = 'failed';
    project.lastBuildError = error.message;
    project.artifacts.buildLogRelativePath = path.relative(env.STORAGE_DIR, buildLogPath).replaceAll(path.sep, '/');
    await project.save();

    job.status = 'failed';
    job.logs = logs;
    job.errorMessage = error.message;
    job.finishedAt = new Date();
    await job.save();

    throw error;
  }
}

export function createPackageId(appName) {
  const slug = slugify(appName, { lower: true, strict: true }) || 'mobileapp';
  return `${env.ANDROID_PACKAGE_PREFIX}.${slug}`;
}
